GET http://localhost:8081/hello
#Accept: application/json

# 单元测试
> {%
client.test("test-hello",function() {
  client.log("测试/hello接口");
  client.log(response.body);
  client.log(JSON.stringify(response.body));

  client.assert(response.status===200,"返回状态不是200");
  client.assert(response.body==="Hello World!","结果效验失败。");
});
%}
###

POST http://localhost:8081/hello/post
Content-Type: application/x-www-form-urlencoded

name=zty

###

GET http://localhost:8081/test/list


###
GET http://localhost:8081/redis/set/111/zty
Accept: application/json

###

GET http://localhost:8081/redis/get/71344628368019456
Accept: application/json

###